### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by osmoc** [contactless/wb-rules#3]
What's the license for source code in this repo?

**Comment by evgeny-boger** [comment]
It's MIT.

Thanks for pointing it out, here you go: https://github.com/contactless/wb-rules/blob/master/LICENSE

By the way, we are always happy to hear what are you're using our Open Source software for! So please don't hesitate to share your experience with us, either positive or negative.

**Comment by osmoc** [comment]
Thanks for clarification. I'm not using this software yet - I'll look for GPLv3+ alternatives first.
